# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := tuto_ray1

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

tuto_ray1: 
	@echo "==== Building tuto_ray1 ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f tuto_ray1.make

clean:
	@${MAKE} --no-print-directory -C . -f tuto_ray1.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   tuto_ray1"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
